# Configuration for the prettier code formatter.
# https://prettier.io/docs/en/options.html
tabWidth: 4
useTabs: false
semi: false
trailingComma: none
bracketSpacing: false
arrowParens: always
endOfLine: lf
